name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Smelly Python: Smell My PR
      # You may pin to the exact commit or the version.
      # uses: smelly-python/smell-my-pr@ca160cd335f89d4e536f17949521b557b9d7a0df
      uses: smelly-python/smell-my-pr@v1.0.0
      with:
        # The folder containing python files for pylint.
        command: # default is smelly-python -d src
        # Github token
        github-token: # default is 
          
