name: 'Smelly Python: Smell My PR'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pipenv
        if: ${{ inputs.install-pipenv }}
        run: |
          sudo apt-get update
          sudo -H pip install -U pipenv

      - name: Setup smelly-python
        run: | 
          pip install smelly-python
          pip install bs4
          pip install pylint 

      - name: Generate report from smelly-python
        shell: bash
        run: smelly-python -d .

      - name: Save output folder with HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: smelly-python-html-report
          path: |
            ${{ github.workspace }}/report/smelly_python/**/*
            !${{ github.workspace }}/report/smelly_python/**/*.md

      - name: Set job summary
        if: always()
        shell: bash
        run: cat ${{ github.workspace }}/report/smelly_python/comment.md >> $GITHUB_STEP_SUMMARY
